# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2419a8832ad80f08eba4719a02e59d1b6a8a248132c85189fbdb1003126f388bffdb210369257ac8bb5b5d6502bf18f605030bc209c84b6e9131d665949ea8b4

test:
  secret_key_base: e0b9853621fe8d2c82c88abcabc83d4fb7093b67f8dad46ff1ee87544f1ed7c71caabcf2667df5d74a2827cf03115ebf906b262d706dd7f97b16cbfcde07efe6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
